config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|de/ do
    resources :tobacco_cipher do
      post 'test_cipher', on: :collection
    end
    resources :contacts
    get 'welcome/index'
    get 'tastes/index'
    root 'welcome#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/taste.rb
class Taste < ApplicationRecord
end

app/models/tobacco_cipher.rb
class TobaccoCipher < ApplicationRecord
  #before_create :set_cipher

  private

  def set_cipher
    self.cipher = generate_cipher
  end

  def generate_cipher
    loop do
      cipher = SecureRandom.random_number(1_000_000_000..10_000_000_000).to_s
      break cipher unless TobaccoCipher.where(cipher: cipher).exists?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options(options = {})
      { locale: I18n.locale }.merge options
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contacts = Contact.new
  end
  def index
    @contacts = Contact.all
  end
  def create
    @contacts = Contact.new(contacts_params)
    if @contacts.save
      ContactsMailer.sent_email(@contacts).deliver
      redirect_to root_path(anchor: 'contacts')
      flash[:yeap] = t(:yeap)
    else
      flash[:not] = t(:not)
      redirect_to root_path(anchor: 'contacts')
    end
  end

  private

  def contacts_params
    params.require(:contacts).permit(:name, :email, :subject, :message)
  end
end

app/controllers/tastes_controller.rb
class TastesController < ApplicationController
  def index
  end
end

app/controllers/tobacco_cipher_controller.rb
class TobaccoCipherController < ApplicationController
  before_action :find_number
  def test_cipher
    if @cipher.exists?
      if @cipher.where(number_cheks: 0).exists?
        @cipher.update(number_cheks: 1)
        flash[:notice] = t(:notice)
      elsif @cipher.where(number_cheks: 1).exists?
        @cipher.update(number_cheks: 2)
        flash[:notice] = t(:notice)
      else
        flash[:error] = t(:error)
      end
    else
      flash[:error] = t(:error)
    end
    redirect_to root_url(anchor: 'services')
  end

  private

  def find_number
    @cipher = TobaccoCipher.where(cipher: cipher_params[:cipher])
  end

  def cipher_params
    params.require(:cipher).permit(:cipher, :number_cheks)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tastes_helper.rb
module TastesHelper
end

app/views/contacts/_new.html.erb
<div id="contacts">
  <div class="contacts_w3layouts_banner_info">
    <h2><%= t(:titlecontacts) %></h2>
    <h3><%= t(:titlecontacts2) %></h3>
    <div class="row">
      <center>
      <%= form_for :contacts, url: { action: 'create', controller: 'contacts'}, remote: true do |f| %>
        <%= f.text_field :name, required: true, placeholder: t(:name),  value: '' %>
        <%= f.text_field :email, required: true, placeholder: t(:email),  value: '' %>
        <%= f.text_field :message, placeholder: t(:message),  value: '' %>
        <%= f.submit t(:submit) %>
      <% end %>
    </div>
  </div>
  <center>
  <% if flash[:yeap] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:yeap] %>
    </div>
  <% end %>
  <% if flash[:not] %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:not] %>
    </div>
  <% end %>
  </center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter48645101 = new Ya.Metrika({
                        id:48645101,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true,
                        webvisor:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/48645101" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119556970-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-119556970-1');
    </script>
    <title>BlackStar</title>

    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Montserrat:400,700' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' %>
    <script>
      new WOW().init();
    </script>
  </head>
  <body>
    <div id="pp">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1><center><%= image_tag("18.png")%> <br> <%= t(:agetitle) %> </center> </h1>
      </div>
      <div class="modal-body">
        <p><%= t(:agetext) %> <br> <br> <%= t(:agetext2)%> </p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn"><h4><%= t(:ageyes)%></h4></a>
        <a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%B5%D0%B4%D0%B5%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%B7%D0%B0%D0%BA%D0%BE%D0%BD_%D0%BE%D1%82_23_%D1%84%D0%B5%D0%B2%D1%80%D0%B0%D0%BB%D1%8F_2013_%D0%B3%D0%BE%D0%B4%D0%B0_%E2%84%96_15-%D0%A4%D0%97" class="btn"><h4><%= t(:ageno) %></h4></a>
      </div>
    </div>
    <div id="pp-bg"></div>
    <div class="startpage">
      <%= image_tag("startpage.jpg")%>
    </div>
    <div class="bg">
			<div id="home" class="header wow bounceInDown" data-wow-delay="0.4s">
					<div class="top-header">
						<div class="container">
              <nav class="top-nav">
                <ul class="top-nav">
                  <% if current_page?(welcome_index_path) %>
                    <li class="active"><a href="#services" class="scroll"><%= t(:tobacco) %></a></li>
                    <li><a href="#tastes" class="scroll"><%= t(:tastes) %></a></li>
                    <li><a href="#port" class="scroll"><%= t(:about) %></a></li>
                  <% else %>
                    <li class="active"><%= link_to t(:tobacco), welcome_index_path(@welcome, anchor: "services", :locale => I18n.locale) %></li>
                    <li><%= link_to t(:tastes), welcome_index_path(@welcome, anchor: "tastes", :locale => I18n.locale ) %></li>
                    <li><%= link_to t(:about), welcome_index_path(@welcome, anchor: "port", :locale => I18n.locale) %></li>
                  <% end %>
                    <li><%= link_to image_tag("de.png", :border => 0, :alt => '', :width => 30, :height => 20, :title => ''), { locale: :de } %></li>
                    <li><%= link_to image_tag("en.png", :border => 0, :alt => '', :width => 40, :height => 30, :title => ''), { locale: :en } %></li>
                </ul>
                <a href="#" id="pull"><%= image_tag("menu-icon.png")%></a>
              </nav>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
      <%= render 'welcome/banner' %>
      <div class="social-tab">
        <div class="social">
          <a href="tel:+79110811486"><%= image_tag("wa.png")%></a>
          <a href="tel:+79523886606"><%= image_tag("phone.png")%></a>
        </div>
      </div>
		</div>
    <%= yield %>
    <script>
      $(function() {
        var pull 		= $('#pull');
          menu 		= $('nav ul');
          menuHeight	= menu.height();
        $(pull).on('click', function(e) {
          e.preventDefault();
          menu.slideToggle();
        });
        $(window).resize(function(){
              var w = $(window).width();
              if(w > 320 && menu.is(':hidden')) {
                menu.removeAttr('style');
              }
          });
      });
    </script>
    <script type="text/javascript">
      jQuery(document).ready(function($) {
        $(".scroll").click(function(event){
          event.preventDefault();
          $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
        });
      });
    </script>
    <script type="application/x-javascript">
      addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
      function hideURLbar(){ window.scrollTo(0,1); }
    </script>
  </body>
</html>

app/views/tobacco_cipher/_form_for_check.html.erb
<div class="agileits_w3layouts_banner_info">
    <h2><%= t(:titlecipher) %></h2>
    <h3><%= t(:titlecipher2) %></h3>
    <div class="row">
    <%= form_for :cipher, url: { action: 'test_cipher', controller: 'tobacco_cipher'}, remote: true do |f| %>
      <%= f.text_field :cipher, required: true, placeholder: t(:entercode),  value: '' %>
      <%= f.submit t(:check) %>
    <% end %>
  </div>
</div><br><br><br>
<center>
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>
</center>

app/views/welcome/_about.html.erb
<div id="port" class="expertise">
  <div class="expertice-grids">
    <div class="col-md-8 expertice-left-grid wow fadeInLeft" data-wow-delay="0.4s">
      <div class="expertise-head">
        <h3><%= t(:about) %></h3>
        <!--<p><%= t(:aboutinfo) %></p>-->
      </div>
      <div class="expertise-left-inner-grids">
        <div class="row">
          <div class="e-left-inner-grid col-sm-6">
            <div class="e-left-inner-grid-right">
              <h4><%= t(:about1) %></h4>
              <p><%= t(:about11) %></p>
            </div>
            <div class="clearfix"> </div>
          </div>
          <div class="e-left-inner-grid col-sm-6">
            <div class="e-left-inner-grid-right">
              <h4><%= t(:about2) %></h4>
              <p><%= t(:about22) %></p>
            </div>
            <div class="clearfix"> </div>
          </div>
        </div>
        <div class="row">
        <div class="e-left-inner-grid col-sm-6">
          <div class="e-left-inner-grid-right">
            <h4><%= t(:about3) %></h4>
            <p><%= t(:about33) %></p>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="e-left-inner-grid col-sm-6">
          <div class="e-left-inner-grid-right">
            <h4><%= t(:about4) %></h4>
            <p><%= t(:about44) %></p>
          </div>
          <div class="clearfix"> </div>
        </div>
      </div>
        <div class="clearfix"> </div>
      </div>
    </div>
    <div class="col-md-4 expertice-right-grid wow fadeInRight" data-wow-delay="0.4s">

    </div>
    <div class="clearfix"> </div>
  </div>
</div>

app/views/welcome/_banner.html.erb
<div class="banner wow fadeIn" data-wow-delay="0.5s">
  <div class="container">
    <div class="banner-info text-center">
      <div class="logonew">
        <div class="star">
          <%= image_tag("logo.png")%>
        </div>
      <%= image_tag("BLACKSTAR2.png")%>
      <%= image_tag("BLACKSTAR1.png")%>
      </div>
      <span> </span>
      <p><h4><%= t(:logo)%></h4></p>
    </div>
  </div>
</div>

app/views/welcome/_bowls.html.erb
<div class="tm-head">
  <h3><%= t(:bowls) %></h3>
</div>
<div class="container_hookah">
  <%= image_tag("bowls1.jpeg")%>
  <%= image_tag("bowls2.jpeg")%>
  <%= image_tag("bowls3.jpeg")%>
</div>

app/views/welcome/_copyright.html.erb
<div class="copy-right">

  <p><%= t(:contacts) %><br>
     <%= t(:mail) %> <a href="mailto:info@newyorkerclub.ru">info@newyorkerclub.ru</a><br>
     <%= t(:phone) %> <a href="tel:+79523886606">+7(952)388-66-06</a><br>
     Whatsapp: <a href="tel:+79110811486">+7(911)081-14-86</a><br>
     Template by <a href="http://w3layouts.com/">W3layouts</a><br><br>
     «STATUS BERATER» GmbH<br>
      Gesellschaft mit beschränkter Haftung<br>
      Nr. HRB 141021<br>
      Potsdamer Strasse 92, 10785 Berlin, Deutschland	<br></p>
  <script type="text/javascript">
    $(document).ready(function() {
      $().UItoTop({ easingType: 'easeOutQuart' });
    });
  </script>
  <a href="#" id="toTop" style="display: block;">
    <span id="toTopHover" style="opacity: 1;"></span>
  </a>
</div>

app/views/welcome/_embers.html.erb
<div class="tm-head">
  <h3><%= t(:embers1) %></h3>
</div>
<center>
<div class="container_tobacco">
  <%= image_tag("embers1.jpeg")%>
  <%= image_tag("embers2.jpeg")%>
</div>
<div class="tm-head">
  <h3><%= t(:embers2) %></h3>
</div>
<div class="container_tobacco">
  <%= image_tag("embers3.jpeg")%>
  <%= image_tag("embers4.jpeg")%>
</div>
</center>

app/views/welcome/_hookah.html.erb
<div class="tm-head">
  <h3><%= t(:hookah1) %></h3>
</div>
<div class="container_hookah">
  <%= image_tag("hookah1.jpg")%>
  <%= image_tag("hookah2.jpg")%>
  <%= image_tag("hookah3.jpg")%>
</div>

app/views/welcome/_portfolio.html.erb
<div class="portfolio">
  <div class="portfolio-top">
    <div class="col-md-8">
      <div class="portfolio-top-left wow fadeInLeft" data-wow-delay="0.4s">
        <h3><%= t(:line) %></h3>
        <p><%= t(:lineinfo) %></p>
        <div class="portfolio-top-left-grids">
          <div class="portfolio-top-left-grid">
            <div class="portfolio-top-left-grid-left">
              <span class="p-icon1"> </span>
            </div>
            <div class="portfolio-top-left-grid-right">
              <h5><%= t(:green) %></h5>
              <p><%= t(:greeninfo) %><br><%= t(:greeninfo2) %></p>
            </div>
            <div class="clearfix"> </div>
          </div>
          <div class="portfolio-top-left-grid">
            <div class="portfolio-top-left-grid-left">
              <span class="p-icon2"> </span>
            </div>
            <div class="portfolio-top-left-grid-right">
              <h5><%= t(:yellow) %></h5>
              <p><%= t(:yellowinfo) %></p>
            </div>
            <div class="clearfix"> </div>
          </div>
          <div class="portfolio-top-left-grid">
            <div class="portfolio-top-left-grid-left">
              <span class="p-icon3"> </span>
            </div>
            <div class="portfolio-top-left-grid-right">
              <h5><%= t(:red) %></h5>
              <p><%= t(:redinfo) %></p>
            </div>
            <div class="clearfix"> </div>
          </div>
        </div>
        <p><%= t(:lineinfo2) %></p>
        <hr>
        <p><%= t(:lineinfo3) %></p>
      </div>
    </div>
    <div class="col-md-4 portfolio-top-right-inner wow fadeInRight" data-wow-delay="0.4s">
      <div class="NYC">
        <%= image_tag("NYCen.jpg")%>
      </div>
    </div>
    <div class="clearfix"></div>
    <br><br><br><br>
    <!---- portfolio-works ---->
    <div id="tastes" class="tastes">
      <div class="tm-head">
        <h3><%= t(:tastes) %></h3>
        <p><%= t(:title2) %></p><br>
      </div>
      <div class="portfolio-works">
        <div class="col-md-4 portfolio-work-grid wow bounceIn" data-wow-delay="0.4s">
          <div class="portfolio-work-grid-pic">
            <div class="front">
              <%= image_tag("tastes/p1.png")%>
            </div>
            <div class="back">
              <%= image_tag("tastes/t1.jpg")%>
            </div>
          </div>
          <div class="portfolio-work-grid-caption">
            <h4>Pink Panter</h4>
            <p><%= t(:t1) %></p>
          </div>
        </div>
        <div class="col-md-4 portfolio-work-grid wow bounceIn" data-wow-delay="0.4s">
          <div class="portfolio-work-grid-pic">
            <div class="front">
              <%= image_tag("tastes/p2.png")%>
            </div>
            <div class="back">
              <%= image_tag("tastes/t2.jpg")%>
            </div>
          </div>
          <div class="portfolio-work-grid-caption">
            <h4>Durian</h4>
            <p><%= t(:t2) %></p>
          </div>
        </div>
        <div class="col-md-4 portfolio-work-grid wow bounceIn" data-wow-delay="0.4s">
          <div class="portfolio-work-grid-pic">
            <div class="front">
              <%= image_tag("tastes/p3.png")%>
            </div>
            <div class="back">
              <%= image_tag("tastes/t3.jpg")%>
            </div>
          </div>
          <div class="portfolio-work-grid-caption">
            <h4>Rose</h4>
            <p><%= t(:t3) %></p>
          </div>
        </div>
        <div class="col-md-4 portfolio-work-grid wow bounceIn" data-wow-delay="0.4s">
          <div class="portfolio-work-grid-pic">
            <div class="front">
              <%= image_tag("tastes/p4.png")%>
            </div>
            <div class="back">
              <%= image_tag("tastes/t4.jpg")%>
            </div>
          </div>
          <div class="portfolio-work-grid-caption">
            <h4>Elki Palki</h4>
            <p><%= t(:t4) %></p>
          </div>
        </div>
        <div class="col-md-4 portfolio-work-grid wow bounceIn" data-wow-delay="0.4s">
          <div class="portfolio-work-grid-pic">
            <div class="front">
              <%= image_tag("tastes/p5.png")%>
            </div>
            <div class="back">
              <%= image_tag("tastes/t5.jpg")%>
            </div>
          </div>
          <div class="portfolio-work-grid-caption">
            <h4>Winnie Pooh</h4>
            <p><%= t(:t5) %></p>
          </div>
        </div>
        <div class="col-md-4 portfolio-work-grid wow bounceIn" data-wow-delay="0.4s">
          <div class="portfolio-work-grid-pic">
            <div class="front">
              <%= image_tag("tastes/p6.png")%>
            </div>
            <div class="back">
              <%= image_tag("tastes/t6.jpg")%>
            </div>
          </div>
          <div class="portfolio-work-grid-caption">
            <h4>Galaxy </h4>
            <p><%= t(:t6) %></p>
          </div>
        </div>
        <div class="clearfix"> </div><br>
        <center><%= link_to t(:alltastes), tastes_index_path(@tastes, anchor: "tastes", :locale => I18n.locale), :class => "leran-more" %></center>
      </div>
    </div>
    <!---- portfolio-works ---->
  </div>
</div>

app/views/welcome/_services.html.erb
<div id="services" class="services">
  <div class="container">
    <div class="service-head text-center">
      <h2><%= t(:tobacco) %></h2>
      <span> </span>
    </div>
    <!--- services-grids --->
    <div class="services-grids text-center">
      <div class="col-md-3">
        <div class="service-grid wow bounceIn" data-wow-delay="0.4s">
          <h3><%= t(:infotobacco) %></h3>
          <p><%= t(:infotobacco2) %></p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="service-grid wow bounceIn" data-wow-delay="0.4s">
          <h3><%= t(:infoaroma) %></h3>
          <p><%= t(:infoaroma2) %></p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="service-grid wow bounceIn" data-wow-delay="0.4s">
          <h3><%= t(:infoconstituents) %></h3>
          <p><%= t(:infoconstituents2) %></p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="service-grid wow bounceIn" data-wow-delay="0.4s">
          <h3><%= t(:infoquality) %></h3>
          <p><%= t(:infoquality2) %></p>
        </div>
      </div>
      <div class="clearfix"> </div>
    </div>
    <!--- services-grids --->
  </div>
</div>
<div class="touching"><b><%= t(:recommend) %></b></div><br>

app/views/welcome/_team.html.erb
<div id="team" class="team-members">
    <div class="wrap">
      <div class="tm-head">
        <h3><%= t(:command) %></h3>
        <p>Наши распространители.</p>
      </div>
      <div class="tm-head-grids">
        <div class="tm-head-grid wow fadeInLeft" data-wow-delay="0.4s">
          <%= image_tag("team-member1.jpg")%>
          <h4>Kimberly Thompson</h4>
          <h5>Marketer</h5>
          <ul class="top-social-icons">
            <li><a class="twitter" href="#"> </a></li>
            <li><a class="facebook" href="#"> </a></li>
            <li><a class="pin" href="#"> </a></li>
            <div class="clear"> </div>
          </ul>
        </div>
        <div class="tm-head-grid wow fadeInUp" data-wow-delay="0.4s">
          <%= image_tag("team-member2.jpg")%>
          <h4>Rico Massimo</h4>
          <h5>Coder</h5>
          <ul class="top-social-icons">
            <li><a class="twitter" href="#"> </a></li>
            <li><a class="facebook" href="#"> </a></li>
            <li><a class="pin" href="#"> </a></li>
            <div class="clear"> </div>
          </ul>
        </div>
        <div class="tm-head-grid wow fadeInRight" data-wow-delay="0.4s">
          <%= image_tag("team-member3.jpg")%>
          <h4>Uku Mason</h4>
          <h5>Graphic Designer</h5>
          <ul class="top-social-icons">
            <li><a class="twitter" href="#"> </a></li>
            <li><a class="facebook" href="#"> </a></li>
            <li><a class="pin" href="#"> </a></li>
            <div class="clear"> </div>
          </ul>
        </div>
        <div class="clearfix"> </div>
      </div>
      <p class="team-info">Proin iaculis purus consequat sem cure  digni ssim donec porttitora entum suscipit aenean rhoncus posuere odio in tincidunt proin iaculis.</p>
    </div>
  </div>

app/views/welcome/_tobacco.html.erb
<div class="tm-head">
  <h3><%= t(:tobaccoinfo) %></h3>
</div>
<center>
<div class="container_tobacco">
  <%= image_tag("tobacco1.jpg")%>
  <%= image_tag("mouthpiece.jpg")%>
  <%= image_tag("NYCde.jpg")%>
</div>
</center>

app/views/welcome/index.html.erb
<%= render 'services' %>
<%= render 'tobacco_cipher/form_for_check' %>
<%= render 'portfolio' %>
<br><br><br><br>
<%= render 'about' %>
<%= render 'hookah' %>
<%= render 'bowls' %>
<%= render 'embers' %>
<%= render 'tobacco'%>
<br><br><br><br><br><br><br><br>
<%= render 'contacts/new' %>
<br><br><br><br>
<%= render 'copyright' %>